/opt/openmon/logs/openmon.log {
    su openmon openmon
    size 50M
    rotate 7
    daily
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    create 0640 openmon openmon
}
